apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"web"},"name":"web","namespace":"ingress-demo"},"spec":{"ports":[{"name":"web-traffic","port":80,"protocol":"TCP","targetPort":3000}],"selector":{"app":"web"},"sessionAffinity":"None","type":"LoadBalancer"}}
  creationTimestamp: "2022-03-09T17:45:25Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: web
  name: web
  namespace: ingress-demo
  resourceVersion: "32321"
  uid: 97dbdfb9-9598-4e96-9b0c-92edaadf6ef1
spec:
  clusterIP: 10.0.188.89
  clusterIPs:
  - 10.0.188.89
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: web-traffic
    nodePort: 30994
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: web
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 52.186.136.161
