name: content-web
'on':
  push:
    branches:
      - main
    paths:
      - content-web/**
      - web.deployment.yml
      - web.service.yml
  workflow_dispatch: null
env:
  imageRepository: content-web
  resourceGroupName: fabmedical-sas
  clusterName: fabmedical-sas
  containerRegistryName: fabmedicalsas
  containerRegistry: fabmedicalsas.azurecr.io
  dockerfilePath: ./content-web
  tag: '${{ github.run_id  }}'
jobs:
  build-and-publish-docker-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ACR
        uses: docker/login-action@v1
        with:
          registry: '${{ env.containerRegistry }}'
          username: '${{ secrets.ACR_USERNAME }}'
          password: '${{ secrets.ACR_PASSWORD }}'
      - name: Build and push an image to container registry
        uses: docker/build-push-action@v2
        with:
          context: '${{ env.dockerfilePath  }}'
          file: '${{ env.dockerfilePath }}/Dockerfile'
          pull: true
          push: true
          tags: >
            ${{ env.containerRegistry }}/${{ env.imageRepository }}:${{ env.tag
            }}

            ${{ env.containerRegistry }}/${{ env.imageRepository }}:latest
      - uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: '${{ env.clusterName }}'
          resource-group: '${{ env.resourceGroupName }}'
      - name: Create ACR credentials secret
        uses: azure/k8s-create-secret@v1
        with:
          container-registry-url: '${{ env.containerRegistry }}.azurecr.io'
          container-registry-username: '${{ secrets.ACR_USERNAME }}'
          container-registry-password: '${{ secrets.ACR_PASSWORD }}'
          secret-name: ingress-demo-secret
          namespace: ingress-demo
          arguments: '--force true'
      - name: Deploy to AKS
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            web.deployment.yml
            web.service.yml
          images: >
            ${{ env.containerRegistry }}.azurecr.io/${{ env.imageRepository
            }}:${{ env.tag }}
          imagepullsecrets: |
            ingress-demo-secret
            namespace: ingress-demo
